a = input("Enter your name:")
b = input("Enter your surname:")
c = input("Enter your favourite animal:")
d = input("Enter your zodiac sign:")
print('Individual gyroscope for the user', a, b)
print('Who were you in last life:', c)
print('Your zodiac sign is ', d, ', so you have a delicate nature.')
